manifest:
  remotes:
    - name: keb-main
      url-base: https://github.com/KyleBrandon
  projects:
    - name: zmk
      remote: keb-main
      revision: kyle-main
      import: app/west.yml
  self:
    path: config
